### ISSUE TITLE
Implement the alerting the alerting functionality

### ISSUE THREAD

**Issue by staschc** [52North/waterinneu#1]

**Comment by EHJ-52n** [comment]
First version implemented in development set-up. Depending on the entry type different term categories are displayed for selection. All form elements are in sync with the configuration of the `subscriptions` module.

![alerting_system_form](https://cloud.githubusercontent.com/assets/3839896/14502416/733da47a-01ab-11e6-9428-a7fcef42d53b.png)

**Comment by EHJ-52n** [comment]
Latest version is deployed in production.
