### ISSUE TITLE
Course object feature missing

### ISSUE THREAD

**Issue by GloryPassarello** [52North/waterinneu#41]
At the moment on the e-learning module there is no feature that allows course administrators to upload course contents. 
On the **'Course outline**' section, it  is not present **Course Object** for **Add Object**. 
On other hands, videos, PDFs, documents and  links cannot be uploaded on the course.

**Comment by EHJ-52n** [comment]
@GloryPassarello 

Is this issue still relevant?

**Comment by GloryPassarello** [comment]
@EHJ-52n 

No, it is fixed now.
I will close the issue. 

Thank you.
