### ISSUE TITLE
Twitter Widget not appearing

### ISSUE THREAD

**Issue by EHJ-52n** [52North/waterinneu#8]
> In my case the Twitter widget is not appearing (FF 44.0.2) on Chrome it shows properly.
> ![wieu_twitter_widget_fail_1-2](https://cloud.githubusercontent.com/assets/3839896/14313135/26f4c924-fbf0-11e5-956c-b0960d05246f.png)
> ![wieu_twitter_widget_fail_2-2](https://cloud.githubusercontent.com/assets/3839896/14313136/295a713c-fbf0-11e5-80f1-da17487b0c3a.png)
> The widget just seems to not be in the HTML code, and no errors are appearing reported in the Console (I can try to debug it if you need).

**Comment by EHJ-52n** [comment]
- Is this issue still happening? I just tested is with FF 45 on ubuntu.
- Do you have any adblock or no-script plugin running?
- What is the network tab saying about requests to 
  - https://syndication.twitter.com/[...], 
  - https://pbs.twimg.com/[...], and 
  - https://platform.twitter.com/widgets.js 
  
  that are failing or returning error codes?

**Comment by DanielDiBe** [comment]
Disabling the Blur component (involved with privacy protection) solved the issue and the widget is appearing once more.

**Comment by EHJ-52n** [comment]
@DanielDiBe Okay, than I can close this issue as it is not a problem of the prototype but the client configuration, right?
