### ISSUE TITLE
Whole accordion heading clickable

### ISSUE THREAD

**Issue by EHJ-52n** [52North/waterinneu#9]
> Not a priority, but making the whole band of each element of the accordion clickable might make easier user interaction (the DIV element of each option). Now only the words and icons are clickable, and some users might tend to click on the blue square to no effect.

**Comment by EHJ-52n** [comment]
Fixed in the latest version. Landing page is already updated, but matchmaking page will be updated soon.

**Comment by DanielDiBe** [comment]
Issue fixed. Thanks.
Maybe we can add a "cursor: pointer" to the CSS of the blue divs (panel-heading class)?

**Comment by EHJ-52n** [comment]
@DanielDiBe Good point regarding the CSS. It is already set in the development environment and will be soon available in the online version.
